default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: password
  host: localhost

  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: budget_app_development

test:
  <<: *default
  database: budget_app_test

production:
  <<: *default
  database: budget_app_production
  username: budget_app
  password: <%= ENV["BUDGET_APP_DATABASE_PASSWORD"] %>
